# -*- coding: utf-8 -*-
"""Quantitative_Grad-CAM_Localization _Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/116quXvPeeixh8fgzLhwbLSnSjIoJSE39
"""

# ============================================================
# Quantitative Grad-CAM Localization Analysis
# ============================================================
#
# Purpose
# -------
# Quantify how strongly Grad-CAM activation overlaps with
# annotated diagnostic structures.
#
# Primary metric:
#     Activation enrichment
#
#     enrichment =
#         activation_inside_GT / GT_area_fraction
#
# where:
#     activation_inside_GT =
#         Grad-CAM activation contained within the GT region
#         divided by total Grad-CAM activation.
#
#     GT_area_fraction =
#         GT region area divided by total image area.
#
# Interpretation:
#     1.0x  = activation proportional to GT area
#     >1.0x = activation enriched within GT
#     <1.0x = activation less concentrated in GT than expected
#              from its area alone
#
# Additional metrics:
#     - activation_inside_GT
#     - GT area fraction
#     - activation enrichment
#     - pointing accuracy
#
# The code calculates metrics independently for each image
# before calculating dataset-level means and medians.
# ============================================================


# ============================================================
# 1. Imports
# ============================================================

import numpy as np
import pandas as pd


# ============================================================
# 2. Ground-truth mask creation
# ============================================================

def create_gt_mask(
    image_shape,
    boxes
):
    """
    Create a binary ground-truth mask from bounding boxes.

    Parameters
    ----------
    image_shape : tuple
        Image shape as (height, width).

    boxes : array-like
        Bounding boxes in XYXY format:
        [x1, y1, x2, y2]

    Returns
    -------
    gt_mask : np.ndarray
        Binary mask with shape (height, width).
        GT pixels = 1
        Background pixels = 0
    """

    height, width = image_shape[:2]

    gt_mask = np.zeros(
        (height, width),
        dtype=np.uint8
    )

    if boxes is None or len(boxes) == 0:
        return gt_mask

    for box in boxes:

        x1, y1, x2, y2 = box

        # Convert coordinates to integer pixel indices.
        x1 = int(np.floor(x1))
        y1 = int(np.floor(y1))
        x2 = int(np.ceil(x2))
        y2 = int(np.ceil(y2))

        # Clip coordinates to image boundaries.
        x1 = max(0, min(x1, width))
        x2 = max(0, min(x2, width))
        y1 = max(0, min(y1, height))
        y2 = max(0, min(y2, height))

        # Fill the bounding-box region.
        gt_mask[y1:y2, x1:x2] = 1

    return gt_mask


# ============================================================
# 3. Normalize Grad-CAM
# ============================================================

def normalize_cam(cam):
    """
    Normalize a Grad-CAM map to the range [0, 1].

    Parameters
    ----------
    cam : np.ndarray
        Raw Grad-CAM activation map.

    Returns
    -------
    normalized_cam : np.ndarray
        CAM normalized to [0, 1].
    """

    cam = np.asarray(cam, dtype=np.float32)

    # Replace invalid values.
    cam = np.nan_to_num(
        cam,
        nan=0.0,
        posinf=0.0,
        neginf=0.0
    )

    # Grad-CAM uses non-negative activation.
    cam = np.maximum(cam, 0)

    cam_min = cam.min()
    cam_max = cam.max()

    # Avoid division by zero for a completely flat CAM.
    if cam_max <= cam_min:
        return np.zeros_like(cam)

    normalized_cam = (
        cam - cam_min
    ) / (
        cam_max - cam_min
    )

    return normalized_cam


# ============================================================
# 4. Calculate activation inside GT
# ============================================================

def calculate_activation_inside_gt(
    cam,
    gt_mask
):
    """
    Calculate the fraction of total Grad-CAM activation
    contained inside the ground-truth region.

    Formula
    -------
    activation_inside_GT =
        sum(CAM within GT) / sum(CAM across image)

    Parameters
    ----------
    cam : np.ndarray
        Normalized Grad-CAM map with values in [0, 1].

    gt_mask : np.ndarray
        Binary GT mask.

    Returns
    -------
    float
        Fraction of total CAM activation located inside GT.
    """

    cam = np.asarray(cam, dtype=np.float32)
    gt_mask = np.asarray(gt_mask, dtype=bool)

    total_activation = np.sum(cam)

    if total_activation <= 0:
        return np.nan

    activation_in_gt = np.sum(
        cam[gt_mask]
    )

    return activation_in_gt / total_activation


# ============================================================
# 5. Calculate GT area fraction
# ============================================================

def calculate_gt_area_fraction(gt_mask):
    """
    Calculate the fraction of the image occupied by the
    ground-truth region.

    Formula
    -------
    GT_area_fraction =
        number of GT pixels / total image pixels

    Parameters
    ----------
    gt_mask : np.ndarray
        Binary GT mask.

    Returns
    -------
    float
        Fraction of image occupied by GT.
    """

    gt_mask = np.asarray(gt_mask, dtype=bool)

    total_pixels = gt_mask.size

    if total_pixels == 0:
        return np.nan

    gt_pixels = np.sum(gt_mask)

    return gt_pixels / total_pixels


# ============================================================
# 6. Calculate activation enrichment
# ============================================================

def calculate_activation_enrichment(
    activation_inside_gt,
    gt_area_fraction
):
    """
    Calculate Grad-CAM activation enrichment within GT.

    Formula
    -------
    enrichment =
        activation_inside_GT / GT_area_fraction

    Interpretation
    --------------
    1.0x:
        CAM activation is proportional to GT area.

    >1.0x:
        CAM is more concentrated inside GT than expected
        based on GT area alone.

    <1.0x:
        CAM is less concentrated inside GT than expected
        based on GT area alone.

    Parameters
    ----------
    activation_inside_gt : float
        Fraction of total CAM activation inside GT.

    gt_area_fraction : float
        Fraction of image occupied by GT.

    Returns
    -------
    float
        Activation enrichment.
    """

    if (
        np.isnan(activation_inside_gt)
        or np.isnan(gt_area_fraction)
        or gt_area_fraction <= 0
    ):
        return np.nan

    return activation_inside_gt / gt_area_fraction


# ============================================================
# 7. Calculate pointing accuracy
# ============================================================

def calculate_pointing_accuracy(
    cam,
    gt_mask
):
    """
    Determine whether the maximum Grad-CAM activation point
    falls inside the ground-truth region.

    Parameters
    ----------
    cam : np.ndarray
        Grad-CAM activation map.

    gt_mask : np.ndarray
        Binary GT mask.

    Returns
    -------
    int
        1 = maximum activation is inside GT
        0 = maximum activation is outside GT
    """

    cam = np.asarray(cam)
    gt_mask = np.asarray(gt_mask, dtype=bool)

    if cam.size == 0 or not np.any(gt_mask):
        return np.nan

    # Location of maximum CAM activation.
    max_index = np.unravel_index(
        np.argmax(cam),
        cam.shape
    )

    return int(gt_mask[max_index])


# ============================================================
# 8. Quantify one image
# ============================================================

def quantify_single_image(
    cam,
    gt_mask
):
    """
    Calculate all quantitative Grad-CAM localization metrics
    for one image.

    Returns
    -------
    dict
        Dictionary containing all image-level metrics.
    """

    # Normalize CAM before quantitative analysis.
    cam = normalize_cam(cam)

    activation_inside_gt = calculate_activation_inside_gt(
        cam,
        gt_mask
    )

    gt_area_fraction = calculate_gt_area_fraction(
        gt_mask
    )

    activation_enrichment = calculate_activation_enrichment(
        activation_inside_gt,
        gt_area_fraction
    )

    pointing_accuracy = calculate_pointing_accuracy(
        cam,
        gt_mask
    )

    return {
        "activation_inside_gt": activation_inside_gt,
        "gt_area_fraction": gt_area_fraction,
        "activation_enrichment": activation_enrichment,
        "pointing_accuracy": pointing_accuracy
    }


# ============================================================
# 9. Process a collection of images
# ============================================================

def quantify_gradcam_dataset(
    image_records
):
    """
    Calculate Grad-CAM metrics for multiple images.

    Parameters
    ----------
    image_records : iterable
        Each record must contain:

            "image_id"
            "class"
            "cam"
            "gt_mask"

        Example:
            {
                "image_id": "V028",
                "class": "VVC",
                "cam": cam_array,
                "gt_mask": mask_array
            }

    Returns
    -------
    pd.DataFrame
        One row per image.
    """

    results = []

    for record in image_records:

        metrics = quantify_single_image(
            cam=record["cam"],
            gt_mask=record["gt_mask"]
        )

        results.append({
            "image_id": record["image_id"],
            "class": record["class"],
            **metrics
        })

    return pd.DataFrame(results)


# ============================================================
# 10. Calculate overall summary statistics
# ============================================================

def summarize_gradcam_results(
    results_df
):
    """
    Calculate overall Grad-CAM summary statistics.

    The mean and median enrichment are calculated from
    image-level enrichment values.

    This is important:
        mean(enrichment per image)

    is NOT equivalent to:

        mean(activation) / mean(GT area)

    Parameters
    ----------
    results_df : pd.DataFrame
        Image-level Grad-CAM results.

    Returns
    -------
    pd.DataFrame
        Overall summary.
    """

    summary = {
        "n": len(results_df),

        "mean_activation_inside_gt":
            results_df["activation_inside_gt"].mean(),

        "mean_gt_area_fraction":
            results_df["gt_area_fraction"].mean(),

        "mean_activation_enrichment":
            results_df["activation_enrichment"].mean(),

        "median_activation_enrichment":
            results_df["activation_enrichment"].median(),

        "pointing_accuracy":
            results_df["pointing_accuracy"].mean()
    }

    return pd.DataFrame([summary])


# ============================================================
# 11. Calculate class-specific summary statistics
# ============================================================

def summarize_gradcam_by_class(
    results_df
):
    """
    Calculate Grad-CAM summary statistics separately for
    each diagnostic category.

    Returns
    -------
    pd.DataFrame
        One row per diagnostic category.
    """

    summary = (
        results_df
        .groupby("class")
        .agg(
            n=("image_id", "count"),

            mean_activation_inside_gt=(
                "activation_inside_gt",
                "mean"
            ),

            mean_gt_area_fraction=(
                "gt_area_fraction",
                "mean"
            ),

            median_activation_enrichment=(
                "activation_enrichment",
                "median"
            ),

            mean_activation_enrichment=(
                "activation_enrichment",
                "mean"
            ),

            pointing_accuracy=(
                "pointing_accuracy",
                "mean"
            )
        )
        .reset_index()
    )

    return summary


# ============================================================
# 12. Convert proportions to percentages
# ============================================================

def add_percentage_columns(
    summary_df
):
    """
    Add percentage-formatted versions of selected metrics.

    The original numeric columns are retained.
    """

    summary_df = summary_df.copy()

    summary_df["pointing_accuracy_percent"] = (
        summary_df["pointing_accuracy"] * 100
    )

    return summary_df


# ============================================================
# 13. Save results
# ============================================================

def save_gradcam_results(
    image_results,
    class_summary,
    overall_summary,
    output_directory
):
    """
    Save image-level and summary Grad-CAM results as CSV files.
    """

    import os

    os.makedirs(
        output_directory,
        exist_ok=True
    )

    image_results.to_csv(
        os.path.join(
            output_directory,
            "gradcam_quantification_image_level.csv"
        ),
        index=False
    )

    class_summary.to_csv(
        os.path.join(
            output_directory,
            "gradcam_quantification_by_class.csv"
        ),
        index=False
    )

    overall_summary.to_csv(
        os.path.join(
            output_directory,
            "gradcam_quantification_overall.csv"
        ),
        index=False
    )


# ============================================================
# 14. Example workflow
# ============================================================
#
# The following example assumes that you have already generated
# the Grad-CAM map and GT mask for each image.
#
# IMPORTANT:
#     Do not calculate enrichment directly from class averages.
#     Calculate enrichment separately for every image first.
# ============================================================

image_records = [
    {
        "image_id": "V028",
        "class": "VVC",
        "cam": cam_v028,
        "gt_mask": gt_mask_v028
    },

    {
        "image_id": "G070",
        "class": "BV",
        "cam": cam_g070,
        "gt_mask": gt_mask_g070
    },

    {
        "image_id": "S030",
        "class": "GU",
        "cam": cam_s030,
        "gt_mask": gt_mask_s030
    }
]


# Calculate image-level metrics.
image_results = quantify_gradcam_dataset(
    image_records
)


# Calculate overall metrics.
overall_summary = summarize_gradcam_results(
    image_results
)


# Calculate class-specific metrics.
class_summary = summarize_gradcam_by_class(
    image_results
)


# Add percentage representation of pointing accuracy.
class_summary = add_percentage_columns(
    class_summary
)


# Display results.
print("\nImage-level results:")
display(image_results)

print("\nClass-level summary:")
display(class_summary)

print("\nOverall summary:")
display(overall_summary)


# ============================================================
# 15. Optional: save results
# ============================================================

OUTPUT_DIR = "/content/drive/MyDrive/HRP5class/GradCAM_quantification"

save_gradcam_results(
    image_results=image_results,
    class_summary=class_summary,
    overall_summary=overall_summary,
    output_directory=OUTPUT_DIR
)

print(f"\nResults saved to: {OUTPUT_DIR}")